/* tslint:disable */
/* eslint-disable */
/**
 * This file was auto-generated by OpenAPI Generator.
 * Do not make direct changes to the file.
 */
export interface InsuranceMember {
  /** Format: int32 */
  id?: number;
  firstName: string;
  lastName: string;
  address1: string;
  address2?: string | null;
  city: string;
  state: string;
  zip: string;
  phoneNumber: string;
  /** Format: email */
  email: string;
  memberPlan: string;
  /** Format: date-time */
  dateOfBirth: string;
  /** Format: date-time */
  policyStartDate: string;
  /** Format: date-time */
  policyEndDate: string;
}
